### ISSUE TITLE
devices_info Module Doesn't Seem to Filter

### ISSUE THREAD

**Issue by jjaswanson4** [ansible-collections/maxamillion.fleetmanager#17]
##### SUMMARY
The 'devices_info' module doesn't seem to filter based off params and instead returns all results from the edge mgmt API

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
consoedot.edgemanagement.devices_info

##### ANSIBLE VERSION
```
ansible [core 2.13.0]
  config file = /root/code/jdc/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Sep 13 2021, 08:18:39) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
Collection                Version
------------------------- -------
consoledot.edgemanagement 0.1.1  
```

##### CONFIGURATION
```
GALAXY_IGNORE_CERTS(/root/code/jdc/ansible.cfg) = True
GALAXY_SERVER_LIST(/root/code/jdc/ansible.cfg) = ['rh-certified_repo', 'community_repo', 'published_repo', 'community_galaxy']
HOST_KEY_CHECKING(/root/code/jdc/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.5 (Ootpa)

##### STEPS TO REPRODUCE
The following task is used as an example:
```yaml
    - name: get information about the device from console dot
      consoledot.edgemanagement.devices_info:
        name: "edge-005056987837"
    register: device_info
```

##### EXPECTED RESULTS
Device should be added to the group specified and Ansible should return "changed" (or ok if already present in group)

The entity being searched for does exist:
```
{
    "Device": {
        "Account": "6341559",
        "Booted": true,
        "Connected": false,
        "CreatedAt": null,
        "DeletedAt": null,
        "DeviceName": "edge-005056987837",
        "DevicesGroups": [],
        "ID": 1911481,
        "ImageID": 0,
        "LastSeen": "2022-07-18T18:51:40.847479+00:00",
        "Name": "edge-005056987837",
        "OrgID": "12868589",
        "RHCClientID": "8eb07905-29cc-4791-b9d9-51d7045eeac7",
        "UUID": "8be2b246-0745-4a16-aa87-178f8734f507",
        "UpdateAvailable": false,
        "UpdateTransaction": [],
        "UpdatedAt": null,
        "org_id": "12868589"
    },
    "DeviceUpdating": false,
    "ImageInfo": null
},
```

##### ACTUAL RESULTS
Debugging the var `device_info` shows that it contains more than a single record, instead showing a similar result to asking the API for devices without any params:

(truncated output, showing the bottom for the total number of results)
```
                }
            ],
            "total": 232
        },
        "failed": false
    }
}
```

#### NOTES
An example query, used via the uri module:
```yaml
  - name: get device ID
    ansible.builtin.uri:
      url: https://console.redhat.com/api/edge/v1/devices?hostname_or_id={{ inventory_hostname }}
    register: device_info
```

**Comment by jjaswanson4** [comment]
Workaround for now, assuming searching by name:
```yaml
    - name: get information about the device from console dot
      consoledot.edgemanagement.devices_info:
      register: device_info
      delegate_to: console.redhat.com
    - name: set device ID fact
      ansible.builtin.set_fact:
        device_id: "{{ device_info.devices | json_query('data[*].Device') | json_query(json_query) | join | int }}"
      vars:
        json_query: "[?Name=='{{ inventory_hostname }}'].ID"
```
